#!/usr/bin/env python3
"""
Summarize VideoDB focus tracking from videodb_events.jsonl.

This script parses the visual index events generated by `videodb_tracker/capture.py`
to compute how much time was spent in each application, providing a summary
similar to `local_tracker/summary.py` but powered entirely by VideoDB's visual analysis.

Usage:
  python videodb_tracker/summary.py [--events-dir /tmp]
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from collections import defaultdict
from pathlib import Path


def default_events_path() -> Path:
    env = os.environ.get("VIDEODB_EVENTS_DIR")
    return Path(env).expanduser() if env else Path("/tmp")


def load_visual_events(path: Path) -> list[dict]:
    events_file = path / "videodb_events.jsonl"
    if not events_file.exists():
        return []
    
    visual_events = []
    latest_player_url = None
    
    with open(events_file, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                e = json.loads(line)
                if e.get("channel") in ("screen_visual", "visual_index"):
                    visual_events.append(e)
                elif e.get("event") == "capture_session.exported":
                    url = e.get("data", {}).get("player_url")
                    if url:
                        latest_player_url = url
            except json.JSONDecodeError:
                continue
                
    return visual_events, latest_player_url


def format_duration(seconds: float) -> str:
    if seconds < 60:
        return f"{seconds:.0f}s"
    m, s = divmod(int(seconds), 60)
    if m < 60:
        return f"{m}m {s}s"
    h, m = divmod(m, 60)
    return f"{h}h {m}m"


def main() -> None:
    p = argparse.ArgumentParser(description="Summarize focus from VideoDB visual index")
    p.add_argument(
        "--events-dir",
        type=Path,
        default=default_events_path(),
        help="Directory containing videodb_events.jsonl",
    )
    args = p.parse_args()

    events, player_url = load_visual_events(args.events_dir)

    if not events:
        print(f"No visual index events found in {args.events_dir / 'videodb_events.jsonl'}.")
        print("Run videodb_tracker/capture.py first to generate screen recording and AI indexing.")
        return

    # Sort by timestamp
    events.sort(key=lambda x: x.get("unix_ts", 0))

    totals: dict[str, float] = defaultdict(float)
    
    for i in range(len(events) - 1):
        app = events[i].get("data", {}).get("text", "Unknown").strip()
        # Clean up common conversational prefixes if the LLM ignores instructions
        app = app.replace("'", "").replace('"', "").strip()
        if app.lower().startswith("the active foreground application is "):
            app = app[37:]
            
        t0 = float(events[i].get("unix_ts", 0))
        t1 = float(events[i + 1].get("unix_ts", 0))
        dt = max(0.0, t1 - t0)
        totals[app] += dt

    # Add the final event duration (assume standard 4s batch if open-ended)
    if events:
        last_app = events[-1].get("data", {}).get("text", "Unknown").strip()
        totals[last_app] += 4.0

    total_tracked = sum(totals.values())
    n = len(events)
    
    ranked = sorted(totals.items(), key=lambda x: -x[1])
    
    print(f"Focus summary ({n} visual samples logged via VideoDB)")
    print(f"Log: {args.events_dir / 'videodb_events.jsonl'}")
    if player_url:
        print(f"Video Link: {player_url}")
    print(f"Tracked window: {format_duration(total_tracked)} total")
    print()
    print(f"{'App':<40} {'Time':>12} {'Share':>8}")
    print("-" * 62)
    for app, sec in ranked:
        pct = (100.0 * sec / total_tracked) if total_tracked > 0 else 0.0
        label = app if len(app) <= 39 else app[:36] + "..."
        print(f"{label:<40} {format_duration(sec):>12} {pct:7.1f}%")
    print()
    print("Where attention went (by share):")
    for app, sec in ranked[:8]:
        pct = (100.0 * sec / total_tracked) if total_tracked > 0 else 0.0
        bar = "█" * max(1, int(pct / 5))
        short = app if len(app) <= 35 else app[:32] + "..."
        print(f"  {short:36} {bar} {pct:.0f}%")


if __name__ == "__main__":
    main()
